name: Manual test of JVMTI packaging
on: 
  pull_request:
jobs:
  jvmti-test:
    name: JVMTI Test
    runs-on: ${{ matrix.operating-system }}
    permissions:
      contents: write
      pull-requests: write
    strategy:
      fail-fast: false
      matrix:
        operating-system: [ macos-latest, ubuntu-latest, windows-latest]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'gradle'
      - name: Create jreleaser work directory
        run: mkdir -p ./build/jreleaser
      - name: Package JMTI
        run: ./gradlew :jvmti:jar