name: Manual test of JVMTI packaging
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:
  jvmti-test:
    runs-on: ${{ matrix.operating-system }}
    permissions:
      contents: write
      pull-requests: write
    strategy:
      fail-fast: false
      matrix:
        operating-system: [ macos-latest, ubuntu-latest, windows-latest]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'gradle'
      - name: Read and update version
        run: |
          if [[ -n "${{ github.event.inputs.version }}" ]]; then
            BASE_VERSION="${{ github.event.inputs.version }}"
          else
            BASE_VERSION=$(grep "^version=" gradle.properties | cut -d'=' -f2)
          fi
          echo "VERSION=${BASE_VERSION}" >> $GITHUB_ENV
          echo "Version: $BASE_VERSION"
      - name: Create jreleaser work directory
        run: mkdir -p ./build/jreleaser
      - name: Package JMTI
        run: ./gradlew :jvmti:jar -Pversion=$VERSION
